# Generated by Django 5.1.1 on 2024-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=25)),
                ('Address', models.TextField()),
                ('Landmark', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=15)),
                ('Dist', models.CharField(max_length=15)),
                ('Added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
