# Generated by Django 5.1.1 on 2024-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=25, verbose_name='Full Name')),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user_detail',
        ),
    ]
